### ISSUE TITLE
Error: ReCaptcha error: Failed to execute Error: Invalid site key or not loaded in api.js: xxx

### ISSUE THREAD

**Issue by CHEWX** [nuxt-community/recaptcha-module#117]
Hi,

Getting the strange error above on my form submission.

```
            try {
                const token = await this.$recaptcha.execute('login')

                let body = new FormData( e.target );

                return axios.post( '/endpoint' , body)
                .then((res) => {

                    if ( res.data.status === 'mail_sent' )
                        e.target.reset()
                })

                // at the end you need to reset recaptcha
                await this.$recaptcha.reset()

            } catch (error) {
                console.log(error)
            }
```

**Comment by mvrlin** [comment]
> Hi,
> 
> 
> 
> Getting the strange error above on my form submission.
> 
> 
> 
> ```
> 
>             try {
> 
>                 const token = await this.$recaptcha.execute('login')
> 
> 
> 
>                 let body = new FormData( e.target );
> 
> 
> 
>                 return axios.post( '/endpoint' , body)
> 
>                 .then((res) => {
> 
> 
> 
>                     if ( res.data.status === 'mail_sent' )
> 
>                         e.target.reset()
> 
>                 })
> 
> 
> 
>                 // at the end you need to reset recaptcha
> 
>                 await this.$recaptcha.reset()
> 
> 
> 
>             } catch (error) {
> 
>                 console.log(error)
> 
>             }
> 
> ```

Hello! You are exiting from your function by returning the axios.post, so the reset function never gets executed.

**Comment by CHEWX** [comment]
Ahhhhhhhh!

**Comment by CHEWX** [comment]
@mvrlin Unfortunately it's still happening, I don't even get a console log of `token` before the axios request.

```
    methods: {
        async submitForm ( e ) {

            try {
                const token = await this.$recaptcha.execute('login')

                console.log('ReCaptcha token:', token)

                let body = new FormData( e.target );

                axios.post( '/endpoint' , body)
                .then((res) => {

                    if ( res.data.status === 'mail_sent' )
                        e.target.reset()
                })

                // at the end you need to reset recaptcha
                await this.$recaptcha.reset()

            } catch (error) {
                console.log(error)
            }

        }
    }
```

**Comment by mvrlin** [comment]
@CHEWX 
You should add an `await` before `axios.post`

**Comment by CHEWX** [comment]
It doesn't help unfortunately, even if I remove the whole axios request, it still fails.

```
            try {
                const token = await this.$recaptcha.execute('login')
            } catch() {}
```

So the token is throwing the error.

**Comment by mvrlin** [comment]
> It doesn't help unfortunately, even if I remove the whole axios request, it still fails.
> 
> 
> 
> ```
> 
>             try {
> 
>                 const token = await this.$recaptcha.execute('login')
> 
>             } catch() {}
> 
> ```
> 
> 
> 
> So the token is throwing the error.

What's the error?

**Comment by CHEWX** [comment]
The same as subject.

**Comment by mvrlin** [comment]
> The same as subject.

Did you passed a valid key in the Nuxt config?

**Comment by CHEWX** [comment]
It's definitely correct because if I change it I get:

> ERROR for site owner: Invalid site key

In the recaptcha itself.

**Comment by CHEWX** [comment]
My current `nuxt.config.js`

```
export default{
     publicRuntimeConfig: {
        recaptcha: {
            hideBadge: true,
            siteKey: '6Ldc0_123456789',
            version: 2,
            mode: 'base'
        }
    },

    recaptcha: {
        hideBadge: true,
        siteKey: '6Ldc0_123456789',
        version: 2,
        mode: 'base'
    }
}
```

**Comment by ka-ke** [comment]
Hi, posting here as the symptoms make it look like the same problem as @CHEWX is experiencing. Error message is "Failed to execute" and we are using v2 with recaptcha@^1.1.1. 

We noticed that our recaptcha implementation has ceased working at some point even though we have been using the same version of the module for 5 months. It was working in September and we are unsure when the behaviour has changed. We are now getting the error from recaptcha.getResponse invocation without more detailed stack trace.

Referring to the earlier posts here, we are also using correct sitekey as invalid value changes the error to "No reCAPTCHA clients exist.". Is there anything else we could try, even to get a more detailed error message? 

Here's the code: 

Recaptcha component in the form
```
        <recaptcha :key="$recaptcha.siteKey" data-size="invisible" />
```

Submit form handler function
```
    async submitForm() {
      try {
        this.$recaptcha.version = 2
        this.$recaptcha.siteKey = this.$config.recaptcha.siteKey
        const token = await this.$recaptcha.getResponse()
        // some code with token, never gets executed currently
      } catch (err) {
        // error handling
      } finally {
        await this.$recaptcha.reset()
      }
    }
```

Recaptcha config (truncated):
```
    recaptcha: {
      hideBadge: true, // Hide badge element (v3 & v2 via size=invisible)
      siteKey: process.env.RECAPTCHA_SITE_KEY, // Site key for requests
      siteKeyV2: process.env.RECAPTCHA_SITE_KEY,
      siteKeyV3: process.env.RECAPTCHA_SITE_KEY_V3,
      version: 3, // Versionsize: 'invisible',
    }
```

**Comment by tienanhemho** [comment]
same issues with recaptcha v3

**Comment by tienanhemho** [comment]
I fixed it.
Open file \node_modules\@nuxtjs\recaptcha\lib\plugin.js then in line 123, look at condition change this.version === 3 to Number(this.version) === 3
![image](https://user-images.githubusercontent.com/11643596/202691871-1b0fb7da-f0fc-4a63-9fe3-86263a8090b3.png)

**Comment by mvrlin** [comment]
@tienanhemho What's the point of passing wrong argument type and expect it to work properly?

Instead of strict equality, I can just use the "loose" one.

**Comment by tienanhemho** [comment]
I don't object to anything. It's just that some people will use .env with RECAPTCHA_VERSION=3 and don't know why this error occurs.
By the way, i found another solution to solve this problem.
![image](https://user-images.githubusercontent.com/11643596/202706881-2f6192b1-5b3c-4ab2-9c8a-4bba09459c66.png)

**Comment by ka-ke** [comment]
@CHEWX I solved my problem by making sure that the "size" matched between the vue component and the recaptcha plugin. I was passing "invisible" to the vue component but the plugin was assuming "normal" size so setting both to "invisible" fixed the issue. This was caused by accidental removal of the size property in recaptcha configs in nuxt.config when both v3 and v2 were managed by the same configs.

**Comment by CHEWX** [comment]
That didn't fix my issue, however I have just re-looked at your example and you're using a different method to get the `token`. Changing this has fixed my issue.

`- const token = await this.$recaptcha.execute('login')`

`+ const token = await this.$recaptcha.getResponse()`

Are the docs wrong? @mvrlin

**Comment by CHEWX** [comment]
Just re-looked at the docs, no they're not wrong, somehow I was using the v3 method. My bad...

**Comment by mvrlin** [comment]
@CHEWX yup
